//! Tool detection and allow-listed request → argument-vector construction.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::paths::{canonical_root, validate_rel_path, PathError};
use crate::process::run_with_limits;

pub const TOOL_NGSPICE: &str = "ngspice";
pub const TOOL_KICAD: &str = "kicad-cli";
const DETECT_TIMEOUT_MS: u64 = 10_000;
const MAX_RUN_DECK_BYTES: u64 = 512 * 1024 + 4096;
const GENERATED_DECK_MARKER: &str = "* --- generated by Engineering Workbench; do not edit ---";

#[derive(Debug, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolDetection {
    pub found: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

pub fn is_known_tool(tool: &str) -> bool {
    matches!(tool, TOOL_NGSPICE | TOOL_KICAD)
}

/// Typed process request from the frontend. Only these two shapes exist; the
/// frontend can never pass raw argument arrays.
#[derive(Debug, serde::Deserialize)]
#[serde(tag = "tool")]
pub enum ToolRunRequest {
    #[serde(rename = "ngspice")]
    Ngspice {
        #[serde(rename = "netlistRelPath")]
        netlist_rel_path: String,
        #[serde(rename = "outputDirRelPath")]
        output_dir_rel_path: String,
    },
    #[serde(rename = "kicad-cli")]
    KicadCli {
        subcommand: String,
        #[serde(rename = "inputRelPath")]
        input_rel_path: String,
        #[serde(rename = "outputRelPath")]
        output_rel_path: String,
    },
}

impl ToolRunRequest {
    pub fn tool_id(&self) -> &'static str {
        match self {
            ToolRunRequest::Ngspice { .. } => TOOL_NGSPICE,
            ToolRunRequest::KicadCli { .. } => TOOL_KICAD,
        }
    }

    /// Validate every embedded path lexically and build the argument vector.
    /// All paths stay relative; the process working directory is the
    /// canonicalised workspace root.
    pub fn build_args(&self) -> Result<Vec<String>, String> {
        match self {
            ToolRunRequest::Ngspice {
                netlist_rel_path,
                output_dir_rel_path,
            } => {
                validate_rel_path(netlist_rel_path).map_err(|e| e.to_string())?;
                validate_rel_path(output_dir_rel_path).map_err(|e| e.to_string())?;
                if output_dir_rel_path != "results" {
                    return Err(
                        "ngspice output directory must be the workspace results folder".into(),
                    );
                }
                if !netlist_rel_path.starts_with("simulations/")
                    || !netlist_rel_path.ends_with(".deck.cir")
                {
                    return Err(
                        "ngspice may execute only a generated deck in the simulations folder"
                            .into(),
                    );
                }
                // `-n` prevents global or per-user .spiceinit startup files
                // from injecting commands outside the validated run deck.
                Ok(vec!["-n".into(), "-b".into(), netlist_rel_path.clone()])
            }
            ToolRunRequest::KicadCli {
                subcommand,
                input_rel_path,
                output_rel_path,
            } => {
                validate_rel_path(input_rel_path).map_err(|e| e.to_string())?;
                validate_rel_path(output_rel_path).map_err(|e| e.to_string())?;
                if !output_rel_path.starts_with("results/") || output_rel_path == input_rel_path {
                    return Err(
                        "kicad-cli outputs must stay under the workspace results folder".into(),
                    );
                }
                let head: &[&str] = match subcommand.as_str() {
                    "sch-erc" => &["sch", "erc", "--format", "json"],
                    "pcb-drc" => &["pcb", "drc", "--format", "json"],
                    "sch-export-netlist" => &["sch", "export", "netlist"],
                    "sch-export-bom" => &["sch", "export", "bom"],
                    "pcb-export-gerbers" => &["pcb", "export", "gerbers"],
                    "pcb-export-drill" => &["pcb", "export", "drill"],
                    "pcb-render" => &["pcb", "render"],
                    other => {
                        return Err(format!(
                            "kicad-cli subcommand {other:?} is not on the allow-list"
                        ))
                    }
                };
                let expected_extension = if subcommand.starts_with("sch-") {
                    ".kicad_sch"
                } else {
                    ".kicad_pcb"
                };
                if !input_rel_path.ends_with(expected_extension) {
                    return Err(format!(
                        "kicad-cli {subcommand} requires an input ending in {expected_extension}"
                    ));
                }
                let mut args: Vec<String> = head.iter().map(|s| s.to_string()).collect();
                args.push("--output".into());
                args.push(output_rel_path.clone());
                args.push(input_rel_path.clone());
                Ok(args)
            }
        }
    }

    /// Validate command-boundary inputs that cannot be represented safely by
    /// the typed argument vector alone. In particular, ngspice interprets the
    /// contents of its input file as commands, so the generated run deck must
    /// be checked immediately before the executable is resolved and spawned.
    pub fn validate_command_boundary(&self, root: &Path) -> Result<(), String> {
        match self {
            ToolRunRequest::Ngspice {
                netlist_rel_path,
                output_dir_rel_path,
            } => validate_ngspice_run_deck_file(root, netlist_rel_path, output_dir_rel_path),
            ToolRunRequest::KicadCli {
                subcommand,
                input_rel_path,
                output_rel_path,
            } => {
                resolve_regular_input(root, input_rel_path, &["pcb", "circuits"], "KiCad input")?;
                let output_is_directory = matches!(
                    subcommand.as_str(),
                    "pcb-export-gerbers" | "pcb-export-drill"
                );
                prepare_output_path(root, output_rel_path, output_is_directory)?;
                Ok(())
            }
        }
    }
}

fn ensure_resolved_within(root: &Path, resolved: &Path, label: &str) -> Result<(), String> {
    if resolved.starts_with(root) {
        Ok(())
    } else {
        Err(format!(
            "{label} resolves outside the authorised workspace root: {:?}",
            resolved
        ))
    }
}

fn lexical_zone<'a>(rel_path: &str, allowed_zones: &'a [&str]) -> Option<&'a str> {
    allowed_zones.iter().copied().find(|zone| {
        rel_path == *zone
            || rel_path
                .strip_prefix(*zone)
                .is_some_and(|tail| tail.starts_with('/'))
    })
}

fn resolve_regular_input(
    root: &Path,
    rel_path: &str,
    allowed_zones: &[&str],
    label: &str,
) -> Result<PathBuf, String> {
    validate_rel_path(rel_path).map_err(|error| error.to_string())?;
    let zone = lexical_zone(rel_path, allowed_zones).ok_or_else(|| {
        format!(
            "{label} must stay in one of these workspace folders: {}",
            allowed_zones.join(", ")
        )
    })?;
    let resolved = root
        .join(rel_path)
        .canonicalize()
        .map_err(|error| format!("{label} could not be resolved at {rel_path:?}: {error}"))?;
    ensure_resolved_within(root, &resolved, label)?;

    let resolved_zone = root
        .join(zone)
        .canonicalize()
        .map_err(|error| format!("{label} zone {zone:?} could not be resolved: {error}"))?;
    ensure_resolved_within(root, &resolved_zone, label)?;
    if !resolved.starts_with(&resolved_zone) {
        return Err(format!(
            "{label} resolves outside its declared {zone:?} workspace zone"
        ));
    }

    let metadata = resolved
        .metadata()
        .map_err(|error| format!("{label} metadata could not be read: {error}"))?;
    if !metadata.is_file() {
        return Err(format!("{label} is not a regular file"));
    }
    Ok(resolved)
}

fn verify_deepest_existing_ancestor(
    root: &Path,
    candidate: &Path,
    label: &str,
) -> Result<PathBuf, String> {
    let mut probe = candidate;
    loop {
        match fs::symlink_metadata(probe) {
            Ok(_) => {
                let resolved = probe.canonicalize().map_err(|error| {
                    format!("{label} existing ancestor could not be resolved: {error}")
                })?;
                ensure_resolved_within(root, &resolved, label)?;
                return Ok(resolved);
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                probe = probe.parent().ok_or_else(|| {
                    format!("{label} has no existing ancestor inside the workspace")
                })?;
            }
            Err(error) => {
                return Err(format!(
                    "{label} existing ancestor could not be inspected: {error}"
                ))
            }
        }
    }
}

fn prepare_output_path(
    root: &Path,
    rel_path: &str,
    output_is_directory: bool,
) -> Result<PathBuf, String> {
    validate_rel_path(rel_path).map_err(|error| error.to_string())?;
    if lexical_zone(rel_path, &["results"]) != Some("results") {
        return Err("external-tool output must stay under the workspace results folder".into());
    }

    let target = root.join(rel_path);
    let directory_to_create = if output_is_directory {
        target.as_path()
    } else {
        target
            .parent()
            .ok_or_else(|| "external-tool output has no parent directory".to_string())?
    };
    verify_deepest_existing_ancestor(root, directory_to_create, "external-tool output")?;
    fs::create_dir_all(directory_to_create)
        .map_err(|error| format!("external-tool output parent could not be created: {error}"))?;

    let resolved_results = root
        .join("results")
        .canonicalize()
        .map_err(|error| format!("workspace results folder could not be resolved: {error}"))?;
    ensure_resolved_within(root, &resolved_results, "workspace results folder")?;
    let resolved_parent = directory_to_create.canonicalize().map_err(|error| {
        format!("external-tool output parent could not be resolved after creation: {error}")
    })?;
    ensure_resolved_within(root, &resolved_parent, "external-tool output")?;
    if !resolved_parent.starts_with(&resolved_results) {
        return Err("external-tool output parent resolves outside the results zone".into());
    }

    match fs::symlink_metadata(&target) {
        Ok(_) => {
            let resolved_target = target.canonicalize().map_err(|error| {
                format!("external-tool output target could not be resolved: {error}")
            })?;
            ensure_resolved_within(root, &resolved_target, "external-tool output")?;
            if !resolved_target.starts_with(&resolved_results) {
                return Err("external-tool output target resolves outside the results zone".into());
            }
            let metadata = resolved_target.metadata().map_err(|error| {
                format!("external-tool output target metadata could not be read: {error}")
            })?;
            if output_is_directory && !metadata.is_dir() {
                return Err("external-tool output directory target is not a directory".into());
            }
            if !output_is_directory && !metadata.is_file() {
                return Err("external-tool output file target is not a regular file".into());
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => {
            return Err(format!(
                "external-tool output target could not be inspected: {error}"
            ))
        }
    }
    Ok(target)
}

fn validate_ngspice_run_deck_file(
    root: &Path,
    netlist_rel_path: &str,
    output_dir_rel_path: &str,
) -> Result<(), String> {
    let resolved =
        resolve_regular_input(root, netlist_rel_path, &["simulations"], "ngspice run deck")?;
    let metadata = resolved
        .metadata()
        .map_err(|error| format!("ngspice run deck metadata could not be read: {error}"))?;
    if metadata.len() > MAX_RUN_DECK_BYTES {
        return Err(format!(
            "ngspice run deck exceeds the {MAX_RUN_DECK_BYTES}-byte command-boundary limit"
        ));
    }

    let deck = fs::read_to_string(&resolved)
        .map_err(|error| format!("ngspice run deck is not valid UTF-8 text: {error}"))?;
    validate_ngspice_run_deck_contents(&deck, output_dir_rel_path)?;
    prepare_output_path(root, output_dir_rel_path, true)?;

    if let Some(output_path) = deck
        .lines()
        .skip_while(|line| *line != GENERATED_DECK_MARKER)
        .skip(1)
        .find_map(|line| line.strip_prefix("wrdata "))
        .and_then(|rest| rest.split_ascii_whitespace().next())
    {
        prepare_output_path(root, output_path, false)?;
    }
    Ok(())
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum GeneratedAnalysis {
    Dc,
    Ac,
    Tran,
}

fn validate_ngspice_run_deck_contents(deck: &str, output_dir_rel_path: &str) -> Result<(), String> {
    if deck.contains('\0') {
        return Err("ngspice run deck contains a NUL byte".into());
    }

    let lines: Vec<&str> = deck.lines().collect();
    let marker_indices: Vec<usize> = lines
        .iter()
        .enumerate()
        .filter_map(|(index, line)| (*line == GENERATED_DECK_MARKER).then_some(index))
        .collect();
    if marker_indices.len() != 1 {
        return Err(
            "ngspice run deck must contain exactly one Engineering Workbench generated marker"
                .into(),
        );
    }

    let marker_index = marker_indices[0];
    reject_unsafe_user_netlist_content(&lines[..marker_index])?;
    validate_generated_control_block(&lines[marker_index + 1..], output_dir_rel_path)
}

/// Mirror the frontend's continuation-aware defence at the process boundary.
/// Comments are inert, while all whitespace and leading `+` continuation
/// markers are removed so split command keywords cannot evade the check.
/// Ngspice's terminal double-backslash continuation is rejected outright.
fn reject_unsafe_user_netlist_content(lines: &[&str]) -> Result<(), String> {
    let mut compact = String::new();
    for line in lines {
        let mut content = line.trim();
        if content.starts_with('*') {
            continue;
        }
        let comment_index = [content.find('$'), content.find(';')]
            .into_iter()
            .flatten()
            .min();
        if let Some(index) = comment_index {
            content = &content[..index];
        }
        content = content.trim_end();
        if content.ends_with(r"\\") {
            return Err(
                "ngspice run deck rejected terminal backslash continuation in user content".into(),
            );
        }
        content = content.strip_prefix('+').unwrap_or(content);
        compact.extend(
            content
                .chars()
                .filter(|character| !character.is_whitespace())
                .flat_map(char::to_lowercase),
        );
    }

    if compact.contains(".control") || compact.contains(".endc") {
        return Err("ngspice run deck rejected forbidden user .control/.endc content".into());
    }
    if [".include", ".incpslt", ".lib"]
        .iter()
        .any(|keyword| compact.contains(keyword))
    {
        return Err("ngspice run deck rejected transitive .include/.incpslt/.lib content".into());
    }
    if ["shell", "system(", "exec("]
        .iter()
        .any(|keyword| compact.contains(keyword))
    {
        return Err("ngspice run deck rejected forbidden user shell/system/exec content".into());
    }
    Ok(())
}

fn validate_generated_control_block(
    lines: &[&str],
    output_dir_rel_path: &str,
) -> Result<(), String> {
    const OP_BLOCK: [&str; 7] = [
        ".control",
        "set filetype=ascii",
        "op",
        "print all",
        "quit",
        ".endc",
        ".end",
    ];

    if lines == OP_BLOCK {
        return Ok(());
    }
    if lines.len() != 9
        || lines[0] != ".control"
        || lines[1] != "set filetype=ascii"
        || lines[2] != "set wr_vecnames"
        || lines[3] != "set wr_singlescale"
        || lines[6] != "quit"
        || lines[7] != ".endc"
        || lines[8] != ".end"
    {
        return Err(
            "ngspice generated control block does not match the Engineering Workbench grammar"
                .into(),
        );
    }

    let analysis = validate_generated_analysis_command(lines[4])?;
    validate_generated_wrdata_command(lines[5], output_dir_rel_path, analysis)
}

fn validate_generated_analysis_command(line: &str) -> Result<GeneratedAnalysis, String> {
    let parts: Vec<&str> = line.split_ascii_whitespace().collect();
    let invalid = || "ngspice generated analysis command is outside the safe grammar".to_string();
    match parts.as_slice() {
        ["dc", source, start, stop, step]
            if is_source_name(source)
                && parse_generated_number(start).is_some()
                && parse_generated_number(stop).is_some()
                && parse_generated_number(step).is_some() =>
        {
            Ok(GeneratedAnalysis::Dc)
        }
        ["ac", "dec", points, start, stop]
            if is_generated_nonnegative_integer(points)
                && parse_generated_number(start).is_some()
                && parse_generated_number(stop).is_some() =>
        {
            Ok(GeneratedAnalysis::Ac)
        }
        ["tran", step, stop]
            if parse_generated_number(step).is_some() && parse_generated_number(stop).is_some() =>
        {
            Ok(GeneratedAnalysis::Tran)
        }
        _ => Err(invalid()),
    }
}

fn is_source_name(value: &str) -> bool {
    let mut characters = value.chars();
    matches!(characters.next(), Some(first) if first.is_ascii_alphabetic())
        && characters.all(|character| character.is_ascii_alphanumeric() || "_.".contains(character))
}

fn is_generated_nonnegative_integer(value: &str) -> bool {
    if !value.is_empty() && value.chars().all(|character| character.is_ascii_digit()) {
        return true;
    }

    // JavaScript switches integer Number stringification to exponential
    // notation at large magnitudes (for example, Math.round(1e21) -> "1e+21").
    let Some((mantissa, exponent)) = value.split_once("e+") else {
        return false;
    };
    let mut dot_count = 0usize;
    !mantissa.is_empty()
        && mantissa.chars().all(|character| {
            if character == '.' {
                dot_count += 1;
                dot_count == 1
            } else {
                character.is_ascii_digit()
            }
        })
        && !mantissa.starts_with('.')
        && !mantissa.ends_with('.')
        && !exponent.is_empty()
        && exponent.chars().all(|character| character.is_ascii_digit())
        && value
            .parse::<f64>()
            .is_ok_and(|number| number.is_finite() && number >= 0.0 && number.fract() == 0.0)
}

/// TypeScript's `Number(value).toExponential(6)` output grammar.
fn parse_generated_number(value: &str) -> Option<f64> {
    let bytes = value.as_bytes();
    let offset = usize::from(bytes.first() == Some(&b'-'));
    if bytes.len() < offset + 11
        || !bytes[offset].is_ascii_digit()
        || bytes[offset + 1] != b'.'
        || !bytes[offset + 2..offset + 8].iter().all(u8::is_ascii_digit)
        || bytes[offset + 8] != b'e'
        || !matches!(bytes[offset + 9], b'+' | b'-')
        || !bytes[offset + 10..].iter().all(u8::is_ascii_digit)
    {
        return None;
    }
    value
        .parse::<f64>()
        .ok()
        .filter(|number| number.is_finite())
}

fn validate_generated_wrdata_command(
    line: &str,
    output_dir_rel_path: &str,
    analysis: GeneratedAnalysis,
) -> Result<(), String> {
    let rest = line.strip_prefix("wrdata ").ok_or_else(|| {
        "ngspice generated wrdata command is outside the safe grammar".to_string()
    })?;
    let path_end = rest
        .find(char::is_whitespace)
        .ok_or_else(|| "ngspice generated wrdata command has no vectors".to_string())?;
    let data_path = &rest[..path_end];
    let expression_text = rest[path_end..].trim();

    if data_path.is_empty()
        || !data_path
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "_./-".contains(character))
    {
        return Err("ngspice generated wrdata path is outside the safe grammar".into());
    }
    validate_rel_path(data_path).map_err(|error| error.to_string())?;
    let output_prefix = format!("{output_dir_rel_path}/");
    if !data_path.starts_with(&output_prefix) {
        return Err(
            "ngspice generated wrdata path is outside the requested output directory".into(),
        );
    }

    let expressions = split_vector_expressions(expression_text)?;
    if expressions.is_empty() {
        return Err("ngspice generated wrdata command has no vectors".into());
    }
    match analysis {
        GeneratedAnalysis::Ac => {
            let mut pairs = expressions.chunks_exact(2);
            for pair in &mut pairs {
                let magnitude = wrapped_vector_argument(&pair[0], "mag")
                    .ok_or_else(|| "ngspice AC wrdata vectors must be mag/ph pairs".to_string())?;
                let phase = wrapped_vector_argument(&pair[1], "ph")
                    .ok_or_else(|| "ngspice AC wrdata vectors must be mag/ph pairs".to_string())?;
                if magnitude != phase || !is_base_vector_expression(magnitude) {
                    return Err(
                        "ngspice AC wrdata vectors must be matching safe mag/ph pairs".into(),
                    );
                }
            }
            if !pairs.remainder().is_empty() {
                return Err("ngspice AC wrdata vectors must be complete mag/ph pairs".into());
            }
        }
        GeneratedAnalysis::Dc | GeneratedAnalysis::Tran => {
            if !expressions
                .iter()
                .all(|expression| is_base_vector_expression(expression))
            {
                return Err("ngspice wrdata vector is outside the safe grammar".into());
            }
        }
    }
    Ok(())
}

fn split_vector_expressions(value: &str) -> Result<Vec<String>, String> {
    let mut expressions = Vec::new();
    let mut depth = 0usize;
    let mut start = None;
    for (index, character) in value.char_indices() {
        if character.is_whitespace() && depth == 0 {
            if let Some(expression_start) = start.take() {
                expressions.push(value[expression_start..index].to_string());
            }
            continue;
        }
        if start.is_none() {
            start = Some(index);
        }
        match character {
            '(' => depth += 1,
            ')' => {
                depth = depth.checked_sub(1).ok_or_else(|| {
                    "ngspice wrdata vector has unbalanced parentheses".to_string()
                })?;
            }
            _ => {}
        }
    }
    if depth != 0 {
        return Err("ngspice wrdata vector has unbalanced parentheses".into());
    }
    if let Some(expression_start) = start {
        expressions.push(value[expression_start..].to_string());
    }
    Ok(expressions)
}

fn wrapped_vector_argument<'a>(expression: &'a str, function: &str) -> Option<&'a str> {
    expression
        .strip_prefix(function)?
        .strip_prefix('(')?
        .strip_suffix(')')
        .map(str::trim)
}

fn is_base_vector_expression(expression: &str) -> bool {
    let expression = expression.trim();
    let safe_atom = |value: &str| {
        !value.is_empty()
            && value
                .chars()
                .all(|character| character.is_ascii_alphanumeric() || "_./+-".contains(character))
    };
    if safe_atom(expression) {
        return true;
    }

    let Some(open_index) = expression.find('(') else {
        return false;
    };
    let Some(inner) = expression
        .get(open_index + 1..)
        .and_then(|rest| rest.strip_suffix(')'))
    else {
        return false;
    };
    let function = &expression[..open_index];
    let mut function_characters = function.chars();
    matches!(function_characters.next(), Some(first) if first.is_ascii_alphabetic())
        && function_characters
            .all(|character| character.is_ascii_alphanumeric() || character == '_')
        && safe_atom(inner.trim())
}

/// Candidate executable names per tool (PATH lookup), most specific first.
fn path_candidates(tool: &str) -> Vec<&'static str> {
    match tool {
        TOOL_NGSPICE => {
            if cfg!(windows) {
                vec!["ngspice_con", "ngspice"]
            } else {
                vec!["ngspice"]
            }
        }
        TOOL_KICAD => vec!["kicad-cli"],
        _ => vec![],
    }
}

/// Well-known install locations checked when PATH lookup fails.
fn well_known_locations(tool: &str) -> Vec<PathBuf> {
    let mut candidates = Vec::new();
    match tool {
        TOOL_NGSPICE => {
            if cfg!(windows) {
                candidates.push(PathBuf::from("C:/Spice64/bin/ngspice_con.exe"));
                candidates.push(PathBuf::from("C:/Spice64/bin/ngspice.exe"));
            } else {
                candidates.push(PathBuf::from("/usr/local/bin/ngspice"));
                candidates.push(PathBuf::from("/opt/homebrew/bin/ngspice"));
            }
        }
        TOOL_KICAD => {
            if cfg!(windows) {
                for major in ["10.0", "9.0", "8.0", "7.0"] {
                    candidates.push(PathBuf::from(format!(
                        "C:/Program Files/KiCad/{major}/bin/kicad-cli.exe"
                    )));
                }
            } else if cfg!(target_os = "macos") {
                candidates.push(PathBuf::from(
                    "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli",
                ));
            } else {
                candidates.push(PathBuf::from("/usr/bin/kicad-cli"));
                candidates.push(PathBuf::from("/usr/local/bin/kicad-cli"));
            }
        }
        _ => {}
    }
    candidates
}

fn version_args(tool: &str) -> &'static [&'static str] {
    match tool {
        TOOL_NGSPICE => &["--version"],
        TOOL_KICAD => &["version"],
        _ => &[],
    }
}

fn supported_executable_name(tool: &str, program: &Path) -> bool {
    let Some(file_name) = program.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    let lower = file_name.to_ascii_lowercase();
    let stem = lower.strip_suffix(".exe").unwrap_or(&lower);
    match tool {
        TOOL_NGSPICE => matches!(stem, "ngspice" | "ngspice_con"),
        TOOL_KICAD => stem == "kicad-cli",
        _ => false,
    }
}

/// Canonicalise and validate an executable selected through the host-owned
/// native picker. The filename and a zero-exit, tool-specific version banner
/// must both match before the path can enter session authority.
pub fn validate_selected_executable(
    tool: &str,
    selected: &Path,
) -> Result<(PathBuf, String), String> {
    if !is_known_tool(tool) {
        return Err(format!("unknown tool {tool:?}"));
    }
    let canonical = fs::canonicalize(selected)
        .map_err(|error| format!("selected executable could not be resolved: {error}"))?;
    if !canonical.is_file() {
        return Err("selected executable is not a regular file".to_string());
    }
    if !supported_executable_name(tool, &canonical) {
        return Err(format!(
            "selected file name is not supported for {tool}; choose the installed {tool} executable"
        ));
    }
    let version = try_version(&canonical, tool).ok_or_else(|| {
        format!(
            "selected file did not pass the {tool} version check; choose the genuine executable"
        )
    })?;
    Ok((canonical, version))
}

fn ngspice_version_line(line: &str) -> bool {
    let lower = line.trim().to_ascii_lowercase();
    let banner = lower.trim_start_matches('*').trim_start();
    let Some(mut remainder) = banner.strip_prefix("ngspice") else {
        return false;
    };
    if let Some(after_console) = remainder.strip_prefix("_con") {
        remainder = after_console;
    }

    let Some(separator) = remainder.chars().next() else {
        return false;
    };
    if separator == '-' {
        remainder = &remainder[separator.len_utf8()..];
    } else if separator.is_ascii_whitespace() {
        remainder = remainder.trim_start();
    } else {
        return false;
    }
    if let Some(after_v) = remainder.strip_prefix('v') {
        remainder = after_v;
    }
    remainder
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_digit())
}

fn kicad_version_line(line: &str) -> bool {
    let line = line.trim();
    let Some((major, remainder)) = line.split_once('.') else {
        return false;
    };
    let minor_digits = remainder
        .chars()
        .take_while(|character| character.is_ascii_digit())
        .count();
    !major.is_empty()
        && major.chars().all(|character| character.is_ascii_digit())
        && minor_digits > 0
        && line.chars().all(|character| {
            character.is_ascii_alphanumeric() || matches!(character, '.' | '-' | '+')
        })
}

/// Extract a version only from the documented output shape for the requested
/// tool. A random executable printing an unrelated line containing digits is
/// deliberately insufficient.
pub fn extract_version_line(tool: &str, stdout: &str, stderr: &str) -> Option<String> {
    stdout
        .lines()
        .chain(stderr.lines())
        .map(str::trim)
        .find(|line| match tool {
            TOOL_NGSPICE => ngspice_version_line(line),
            TOOL_KICAD => kicad_version_line(line),
            _ => false,
        })
        .map(|line| line.chars().take(200).collect())
}

fn version_from_probe(
    program: &Path,
    tool: &str,
    outcome: &crate::process::ProcessOutcome,
) -> Option<String> {
    if !supported_executable_name(tool, program)
        || outcome.exit_code != Some(0)
        || outcome.timed_out
        || outcome.cancelled
    {
        return None;
    }
    extract_version_line(tool, &outcome.stdout, &outcome.stderr)
}

fn try_version(program: &Path, tool: &str) -> Option<String> {
    if !supported_executable_name(tool, program) {
        return None;
    }
    let mut command = Command::new(program);
    command.args(version_args(tool));
    match run_with_limits(command, Some(DETECT_TIMEOUT_MS), None) {
        Ok(outcome) => version_from_probe(program, tool, &outcome),
        _ => None,
    }
}

fn path_locations(tool: &str) -> Vec<PathBuf> {
    let Some(path) = std::env::var_os("PATH") else {
        return Vec::new();
    };
    let mut locations = Vec::new();
    for directory in std::env::split_paths(&path) {
        for name in path_candidates(tool) {
            if cfg!(windows) {
                locations.push(directory.join(format!("{name}.exe")));
            }
            locations.push(directory.join(name));
        }
    }
    locations
}

fn detected_at(tool: &str, candidate: &Path) -> Option<ToolDetection> {
    let (canonical, version) = validate_selected_executable(tool, candidate).ok()?;
    Some(ToolDetection {
        found: true,
        path: Some(canonical.to_string_lossy().into_owned()),
        version: Some(version),
        error: None,
    })
}

/// Detect a tool from a session-selected, canonical host path when present.
/// Otherwise, search only host-controlled PATH and supported install
/// locations. No renderer-provided executable path reaches this function.
pub fn detect_tool(tool: &str, selected_path: Option<&Path>) -> ToolDetection {
    if !is_known_tool(tool) {
        return ToolDetection {
            found: false,
            path: None,
            version: None,
            error: Some(format!("unknown tool {tool:?}")),
        };
    }

    if let Some(selected) = selected_path {
        return match validate_selected_executable(tool, selected) {
            Ok((canonical, version)) => ToolDetection {
                found: true,
                path: Some(canonical.to_string_lossy().into_owned()),
                version: Some(version),
                error: None,
            },
            Err(error) => ToolDetection {
                found: false,
                path: Some(selected.to_string_lossy().into_owned()),
                version: None,
                error: Some(error),
            },
        };
    }

    for location in path_locations(tool) {
        if location.is_file() {
            if let Some(detection) = detected_at(tool, &location) {
                return detection;
            }
        }
    }
    for location in well_known_locations(tool) {
        if location.is_file() {
            if let Some(detection) = detected_at(tool, &location) {
                return detection;
            }
        }
    }
    ToolDetection {
        found: false,
        path: None,
        version: None,
        error: Some(format!(
            "{tool} was not found on PATH or in well-known install locations"
        )),
    }
}

/// Resolve the exact canonical program to execute for a run request.
pub fn resolve_program(tool: &str, selected_path: Option<&Path>) -> Result<PathBuf, String> {
    let detection = detect_tool(tool, selected_path);
    match (detection.found, detection.path) {
        (true, Some(p)) => Ok(PathBuf::from(p)),
        _ => Err(detection
            .error
            .unwrap_or_else(|| format!("{tool} is not available"))),
    }
}

/// Ensure the workspace root exists and is a directory before running.
pub fn validated_root(root: &str) -> Result<PathBuf, PathError> {
    canonical_root(root)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn isolated_test_root(name: &str) -> PathBuf {
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root =
            std::env::temp_dir().join(format!("ewb-tools-{name}-{}-{nonce}", std::process::id()));
        fs::create_dir_all(&root).unwrap();
        root.canonicalize().unwrap()
    }

    const OP_CONTROL: &[&str] = &[
        ".control",
        "set filetype=ascii",
        "op",
        "print all",
        "quit",
        ".endc",
        ".end",
    ];

    fn run_deck(user_body: &str, generated_control: &[&str]) -> String {
        format!(
            "{user_body}\n\n{GENERATED_DECK_MARKER}\n{}\n",
            generated_control.join("\n")
        )
    }

    fn probe_outcome(
        exit_code: Option<i32>,
        stdout: &str,
        stderr: &str,
    ) -> crate::process::ProcessOutcome {
        crate::process::ProcessOutcome {
            exit_code,
            stdout: stdout.into(),
            stderr: stderr.into(),
            timed_out: false,
            cancelled: false,
            truncated: false,
            duration_ms: 1,
        }
    }

    #[test]
    fn ngspice_args_are_batch_mode_with_relative_netlist() {
        let req = ToolRunRequest::Ngspice {
            netlist_rel_path: "simulations/run.deck.cir".into(),
            output_dir_rel_path: "results".into(),
        };
        assert_eq!(
            req.build_args().unwrap(),
            vec!["-n", "-b", "simulations/run.deck.cir"]
        );
    }

    #[test]
    fn kicad_subcommands_map_to_fixed_argument_vectors() {
        let req = ToolRunRequest::KicadCli {
            subcommand: "pcb-drc".into(),
            input_rel_path: "pcb/board.kicad_pcb".into(),
            output_rel_path: "results/drc.report.json".into(),
        };
        assert_eq!(
            req.build_args().unwrap(),
            vec![
                "pcb",
                "drc",
                "--format",
                "json",
                "--output",
                "results/drc.report.json",
                "pcb/board.kicad_pcb"
            ]
        );
    }

    #[test]
    fn unknown_kicad_subcommands_are_rejected() {
        let req = ToolRunRequest::KicadCli {
            subcommand: "pcb-nuke; rm -rf /".into(),
            input_rel_path: "pcb/board.kicad_pcb".into(),
            output_rel_path: "results/x".into(),
        };
        assert!(req.build_args().unwrap_err().contains("allow-list"));
    }

    #[test]
    fn tool_outputs_and_inputs_are_confined_to_declared_workspace_zones() {
        let wrong_ngspice_output = ToolRunRequest::Ngspice {
            netlist_rel_path: "simulations/run.deck.cir".into(),
            output_dir_rel_path: "circuits".into(),
        };
        assert!(wrong_ngspice_output.build_args().is_err());

        let user_netlist = ToolRunRequest::Ngspice {
            netlist_rel_path: "circuits/user.cir".into(),
            output_dir_rel_path: "results".into(),
        };
        assert!(user_netlist.build_args().is_err());

        let clobber_manifest = ToolRunRequest::KicadCli {
            subcommand: "sch-erc".into(),
            input_rel_path: "circuits/design.kicad_sch".into(),
            output_rel_path: "workbench.json".into(),
        };
        assert!(clobber_manifest.build_args().is_err());

        let wrong_input_type = ToolRunRequest::KicadCli {
            subcommand: "pcb-drc".into(),
            input_rel_path: "circuits/design.kicad_sch".into(),
            output_rel_path: "results/drc.json".into(),
        };
        assert!(wrong_input_type.build_args().is_err());
    }

    #[test]
    fn command_boundary_accepts_safe_inputs_and_host_creates_output_parents() {
        let root = isolated_test_root("safe-boundary");
        fs::create_dir_all(root.join("simulations")).unwrap();
        fs::create_dir_all(root.join("pcb")).unwrap();
        fs::write(
            root.join("simulations/run.deck.cir"),
            run_deck(
                "* title\nV1 in 0 1\nR1 in 0 1k",
                &[
                    ".control",
                    "set filetype=ascii",
                    "set wr_vecnames",
                    "set wr_singlescale",
                    "tran 1.000000e-5 1.000000e-3",
                    "wrdata results/nested/tran.data.txt v(in)",
                    "quit",
                    ".endc",
                    ".end",
                ],
            ),
        )
        .unwrap();
        fs::write(root.join("pcb/board.kicad_pcb"), "(kicad_pcb)").unwrap();

        let ngspice = ToolRunRequest::Ngspice {
            netlist_rel_path: "simulations/run.deck.cir".into(),
            output_dir_rel_path: "results".into(),
        };
        ngspice.validate_command_boundary(&root).unwrap();
        assert!(root.join("results").is_dir());
        assert!(root.join("results/nested").is_dir());

        let kicad_file = ToolRunRequest::KicadCli {
            subcommand: "pcb-drc".into(),
            input_rel_path: "pcb/board.kicad_pcb".into(),
            output_rel_path: "results/checks/drc.json".into(),
        };
        kicad_file.validate_command_boundary(&root).unwrap();
        assert!(root.join("results/checks").is_dir());

        let kicad_directory = ToolRunRequest::KicadCli {
            subcommand: "pcb-export-gerbers".into(),
            input_rel_path: "pcb/board.kicad_pcb".into(),
            output_rel_path: "results/fabrication/gerbers".into(),
        };
        kicad_directory.validate_command_boundary(&root).unwrap();
        assert!(root.join("results/fabrication/gerbers").is_dir());
    }

    #[cfg(unix)]
    #[test]
    fn command_boundary_rejects_input_and_output_symlink_escapes() {
        use std::os::unix::fs::symlink;

        let base = isolated_test_root("symlink-escape-base");
        let root = base.join("workspace");
        let outside = base.join("outside");
        fs::create_dir_all(root.join("pcb")).unwrap();
        fs::create_dir_all(&outside).unwrap();
        fs::write(outside.join("board.kicad_pcb"), "(kicad_pcb)").unwrap();
        symlink(
            outside.join("board.kicad_pcb"),
            root.join("pcb/board.kicad_pcb"),
        )
        .unwrap();

        let input_escape = ToolRunRequest::KicadCli {
            subcommand: "pcb-drc".into(),
            input_rel_path: "pcb/board.kicad_pcb".into(),
            output_rel_path: "results/drc.json".into(),
        };
        let input_error = input_escape.validate_command_boundary(&root).unwrap_err();
        assert!(input_error.contains("outside the authorised workspace root"));

        fs::remove_file(root.join("pcb/board.kicad_pcb")).unwrap();
        fs::write(root.join("pcb/board.kicad_pcb"), "(kicad_pcb)").unwrap();
        symlink(&outside, root.join("results")).unwrap();
        let output_error = input_escape.validate_command_boundary(&root).unwrap_err();
        assert!(output_error.contains("outside the authorised workspace root"));
        assert!(!outside.join("drc.json").exists());
    }

    #[cfg(windows)]
    #[test]
    fn command_boundary_rejects_windows_junction_input_and_output_escapes() {
        use std::os::windows::process::CommandExt;

        let base = isolated_test_root("junction-escape-base");
        let root = base.join("workspace");
        let outside = base.join("outside");
        fs::create_dir_all(root.join("pcb")).unwrap();
        fs::create_dir_all(&outside).unwrap();
        fs::write(root.join("pcb/board.kicad_pcb"), "(kicad_pcb)").unwrap();

        let command_path = |path: &Path| {
            let value = path.to_string_lossy();
            value
                .strip_prefix(r"\\?\")
                .unwrap_or(value.as_ref())
                .to_string()
        };
        let command = format!(
            "mklink /J \"{}\" \"{}\" >nul",
            command_path(&root.join("results")),
            command_path(&outside)
        );
        let mut junction_command = Command::new("cmd");
        junction_command.args(["/D", "/S", "/C"]);
        junction_command.raw_arg(format!("\"{command}\""));
        let status = junction_command.status().unwrap();
        if !status.success() {
            eprintln!("junction creation is unavailable on this Windows host; test skipped");
            return;
        }

        let request = ToolRunRequest::KicadCli {
            subcommand: "pcb-drc".into(),
            input_rel_path: "pcb/board.kicad_pcb".into(),
            output_rel_path: "results/drc.json".into(),
        };
        let error = request.validate_command_boundary(&root).unwrap_err();
        assert!(error.contains("outside the authorised workspace root"));
        assert!(!outside.join("drc.json").exists());
        fs::remove_dir(root.join("results")).unwrap();

        fs::remove_dir_all(root.join("pcb")).unwrap();
        fs::write(outside.join("board.kicad_pcb"), "(kicad_pcb)").unwrap();
        let input_command = format!(
            "mklink /J \"{}\" \"{}\" >nul",
            command_path(&root.join("pcb")),
            command_path(&outside)
        );
        let mut junction_command = Command::new("cmd");
        junction_command.args(["/D", "/S", "/C"]);
        junction_command.raw_arg(format!("\"{input_command}\""));
        let status = junction_command.status().unwrap();
        assert!(status.success(), "input junction creation failed");
        let error = request.validate_command_boundary(&root).unwrap_err();
        assert!(error.contains("outside the authorised workspace root"));
        fs::remove_dir(root.join("pcb")).unwrap();
    }

    #[test]
    fn injection_attempts_in_paths_are_rejected_before_spawn() {
        for evil in [
            "../outside.cir",
            "/abs/path.cir",
            "C:/x.cir",
            "a\\b.cir",
            "x/../../y",
        ] {
            let req = ToolRunRequest::Ngspice {
                netlist_rel_path: evil.into(),
                output_dir_rel_path: "results".into(),
            };
            assert!(req.build_args().is_err(), "{evil} should be rejected");
        }
        // Argument-vector spawning means shell metacharacters are inert, but the
        // path validator still rejects separator tricks embedded in them.
        let quoted = ToolRunRequest::Ngspice {
            netlist_rel_path: "a.cir; rm -rf /".into(),
            output_dir_rel_path: "results".into(),
        };
        // "; rm -rf /" contains '/' segments that make it a multi-segment path
        // with empty component (" /" trailing) — rejected lexically.
        assert!(quoted.build_args().is_err());
    }

    #[test]
    fn unknown_tools_and_invalid_selected_paths_fail_detection() {
        let det = detect_tool("make", None);
        assert!(!det.found);
        let det = detect_tool(TOOL_NGSPICE, Some(Path::new("Z:/nope/ngspice.exe")));
        assert!(!det.found);
        assert!(det.error.unwrap().contains("could not be resolved"));

        let unrelated = std::env::temp_dir().join(format!(
            "ewb-unrelated-tool-{}-python.exe",
            std::process::id()
        ));
        fs::write(&unrelated, "not an executable").unwrap();
        let det = detect_tool(TOOL_KICAD, Some(&unrelated));
        let _ = fs::remove_file(&unrelated);
        assert!(!det.found);
        assert!(det.error.unwrap().contains("name is not supported"));
    }

    #[test]
    fn valid_generated_run_decks_pass_the_command_boundary_grammar() {
        let user_body = "* RC circuit\nV1 in 0 1\nR1 in out 1k\nC1 out 0 1u";
        let generated_controls: [&[&str]; 4] = [
            OP_CONTROL,
            &[
                ".control",
                "set filetype=ascii",
                "set wr_vecnames",
                "set wr_singlescale",
                "dc V1 -1.000000e+0 1.000000e+0 1.000000e-1",
                "wrdata results/dc.data.txt v(out) i(V1)",
                "quit",
                ".endc",
                ".end",
            ],
            &[
                ".control",
                "set filetype=ascii",
                "set wr_vecnames",
                "set wr_singlescale",
                "ac dec 20 1.000000e+1 1.000000e+5",
                "wrdata results/ac.data.txt mag(v(out)) ph(v(out)) mag(i(V1)) ph(i(V1))",
                "quit",
                ".endc",
                ".end",
            ],
            &[
                ".control",
                "set filetype=ascii",
                "set wr_vecnames",
                "set wr_singlescale",
                "tran 1.000000e-5 1.000000e-3",
                "wrdata results/tran.data.txt v( out ) branch/current",
                "quit",
                ".endc",
                ".end",
            ],
        ];

        for control in generated_controls {
            let deck = run_deck(user_body, control);
            assert!(
                validate_ngspice_run_deck_contents(&deck, "results").is_ok(),
                "valid generated deck was rejected:\n{deck}"
            );
        }
    }

    #[test]
    fn generated_number_formatting_edges_remain_grammar_compatible() {
        let body = "* title\nV1 in 0 1\nR1 in out 1k";
        for control in [
            &[
                ".control",
                "set filetype=ascii",
                "set wr_vecnames",
                "set wr_singlescale",
                "ac dec 0 1.000000e+1 1.000000e+5",
                "wrdata results/ac.data.txt mag(v(out)) ph(v(out))",
                "quit",
                ".endc",
                ".end",
            ][..],
            &[
                ".control",
                "set filetype=ascii",
                "set wr_vecnames",
                "set wr_singlescale",
                "tran 1.000000e+0 1.000000e+0",
                "wrdata results/tran.data.txt v(out)",
                "quit",
                ".endc",
                ".end",
            ][..],
        ] {
            assert!(
                validate_ngspice_run_deck_contents(&run_deck(body, control), "results").is_ok(),
                "safe TypeScript-formatted command was rejected: {control:?}"
            );
        }
        assert!(is_generated_nonnegative_integer("1e+21"));
    }

    #[test]
    fn user_control_and_process_escape_content_is_rejected_even_when_continued() {
        let adversarial_bodies = [
            "* direct control\n.control\nshell whoami",
            "* split control\n.cont\n+rol\nR1 1 0 1k",
            "* split shell\nsh\n+ell whoami\nR1 1 0 1k",
            "* split system\nsyst\n+em(whoami)\nR1 1 0 1k",
            "* split exec\nex\n+ec(whoami)\nR1 1 0 1k",
            "* terminal continuation\n.cont\\\\\nrol\nsh\\\\\nell whoami\n.en\\\\\ndc",
            "* transitive control\n.include payload.cir\nR1 1 0 1k",
            "* transitive library\n.lib payload.lib dangerous\nR1 1 0 1k",
            "* compatibility include\n.incpslt payload.cir\nR1 1 0 1k",
        ];

        for body in adversarial_bodies {
            let deck = run_deck(body, OP_CONTROL);
            assert!(
                validate_ngspice_run_deck_contents(&deck, "results").is_err(),
                "adversarial user content was accepted:\n{body}"
            );
        }
    }

    #[test]
    fn comments_are_inert_but_duplicate_generated_markers_are_rejected() {
        let comments = "* title\n* .control shell system exec .include x\nRsystem_load 1 0 1k\nXexecutor 1 0 safe_model ; shell is only a comment";
        assert!(
            validate_ngspice_run_deck_contents(&run_deck(comments, OP_CONTROL), "results").is_ok()
        );

        let duplicate = run_deck(
            &format!("* title\n{GENERATED_DECK_MARKER}\nR1 1 0 1k"),
            OP_CONTROL,
        );
        assert!(validate_ngspice_run_deck_contents(&duplicate, "results").is_err());
    }

    #[test]
    fn edited_generated_control_commands_and_output_paths_are_rejected() {
        let body = "* title\nV1 in 0 1\nR1 in out 1k";
        let cases: [&[&str]; 4] = [
            &[
                ".control",
                "set filetype=ascii",
                "set wr_vecnames",
                "set wr_singlescale",
                "tran 1.000000e-5 1.000000e-3; shell whoami",
                "wrdata results/x.data.txt v(out)",
                "quit",
                ".endc",
                ".end",
            ],
            &[
                ".control",
                "set filetype=ascii",
                "set wr_vecnames",
                "set wr_singlescale",
                "tran 1.000000e-5 1.000000e-3",
                "wrdata ../escape.data.txt v(out)",
                "quit",
                ".endc",
                ".end",
            ],
            &[
                ".control",
                "set filetype=ascii",
                "set wr_vecnames",
                "set wr_singlescale",
                "tran 1.000000e-5 1.000000e-3",
                "wrdata elsewhere/x.data.txt v(out)",
                "quit",
                ".endc",
                ".end",
            ],
            &[
                ".control",
                "set filetype=ascii",
                "set wr_vecnames",
                "set wr_singlescale",
                "tran 1.000000e-5 1.000000e-3",
                "wrdata results/x.data.txt v(out);shell whoami",
                "quit",
                ".endc",
                ".end",
            ],
        ];

        for control in cases {
            assert!(
                validate_ngspice_run_deck_contents(&run_deck(body, control), "results").is_err(),
                "edited generated block was accepted: {control:?}"
            );
        }
    }

    #[test]
    fn supported_executable_names_cover_console_and_cross_platform_variants() {
        for program in [
            "ngspice",
            "ngspice.exe",
            "ngspice_con",
            "ngspice_con.exe",
            "/usr/local/bin/ngspice",
            "C:/Spice64/bin/ngspice_con.exe",
        ] {
            assert!(supported_executable_name(TOOL_NGSPICE, Path::new(program)));
        }
        for program in [
            "kicad-cli",
            "kicad-cli.exe",
            "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli",
            "C:/Program Files/KiCad/9.0/bin/kicad-cli.exe",
        ] {
            assert!(supported_executable_name(TOOL_KICAD, Path::new(program)));
        }
        assert!(!supported_executable_name(
            TOOL_KICAD,
            Path::new("python.exe")
        ));
        assert!(!supported_executable_name(
            TOOL_NGSPICE,
            Path::new("ngspice-helper.exe")
        ));
    }

    #[test]
    fn windows_kicad_discovery_includes_current_major() {
        if cfg!(windows) {
            let locations = well_known_locations(TOOL_KICAD);
            assert!(locations.iter().any(|path| {
                path.to_string_lossy()
                    .replace('\\', "/")
                    .ends_with("/KiCad/10.0/bin/kicad-cli.exe")
            }));
        }
    }

    #[test]
    fn version_line_extraction_requires_tool_specific_output() {
        assert_eq!(
            extract_version_line(
                TOOL_NGSPICE,
                "******\n** ngspice-44 : Circuit level simulation program\n",
                ""
            ),
            Some("** ngspice-44 : Circuit level simulation program".to_string())
        );
        assert_eq!(
            extract_version_line(TOOL_KICAD, "8.0.4\n", ""),
            Some("8.0.4".to_string())
        );
        assert_eq!(
            extract_version_line(TOOL_NGSPICE, "unrelated tool 44", ""),
            None
        );
        assert_eq!(
            extract_version_line(TOOL_NGSPICE, "fake wrapper ngspice-44", ""),
            None
        );
        assert_eq!(extract_version_line(TOOL_KICAD, "Python 3.12.2", ""), None);
        assert_eq!(extract_version_line(TOOL_NGSPICE, "44", ""), None);
    }

    #[test]
    fn version_probe_rejects_nonzero_exit_and_unrelated_executables_with_digits() {
        let failed = probe_outcome(
            Some(1),
            "** ngspice-44 : Circuit level simulation program",
            "",
        );
        assert_eq!(
            version_from_probe(Path::new("ngspice.exe"), TOOL_NGSPICE, &failed),
            None
        );

        let digits = probe_outcome(Some(0), "8.0.4", "");
        assert_eq!(
            version_from_probe(Path::new("python.exe"), TOOL_KICAD, &digits),
            None
        );
        assert_eq!(
            version_from_probe(Path::new("kicad-cli.exe"), TOOL_KICAD, &digits),
            Some("8.0.4".into())
        );

        let ngspice = probe_outcome(
            Some(0),
            "",
            "** ngspice-46 : Circuit level simulation program",
        );
        assert_eq!(
            version_from_probe(Path::new("ngspice_con.exe"), TOOL_NGSPICE, &ngspice),
            Some("** ngspice-46 : Circuit level simulation program".into())
        );
    }
}
